server:
  # port 번호가 0번이면 랜덤으로 배정된다.
  port: 0

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: sseioul@gmail.com
    password: jgjqmluzyyhzetzy
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  application:
    name: user-service
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  datasource:
    url: jdbc:mysql://j8c209.p.ssafy.io:3308/devday?useUnicode=true&serverTimezone=Asia/Seoul&characterEncoding=utf8
    username: root
    password: devday1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql   # 추가 해준 부분
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect # 추가 해준 부분
    hibernate:
      ddl-auto: create
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        default_batch_fetch_size: 500
  redis:
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
    port: 6379
    host: localhost

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

logging:
  level:
    com.example.userservice.client: DEBUG

batchSize: 500

gateway:
  ip: 172.18.0.6

token:
  secret: dyAeHubOOc8KaOfYB6XEQoEj1QzRlVgtjNL8PYs1A1tymZvvqkcEU7L1imkKHeDa

cloud:
  aws:
    region:
      static: ap-northeast-2
    s3:
      bucket: devday-bucket
    credentials:
      access-key: AKIAXEUXRPXDUUVY2A5E
      secret-key: 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
    stack:
      auto: false

