spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:pay-service;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    show-sql: true
